export const MODULE_NAME = 'CHANGE_MCC'

/* actions */
export const GET_MCC_CATEGORIES = 'GET_MCC_CATEGORIES'
export const GET_MCC_CATEGORIES_LOADING = 'GET_MCC_CATEGORIES_LOADING'
export const CHANGE_MCC_CATEGORY = 'CHANGE_MCC_CATEGORY'
export const CHANGE_MCC_CATEGORY_LOADING = 'CHANGE_MCC_CATEGORY_LOADING'
